apiVersion: integration/v1
kind: Step
name: image-build
version: 3
summary: Build Image
description: Build a docker image from the git resource provided.
build:
  apiVersion: build/v1
  kind: Docker
publish:
  repository: relaysh/kaniko-step-image-build
schemas:
  spec:
    source: file
    file: spec.schema.json
examples:
- summary: Build a docker image and push to DockerHub
  content:
    apiVersion: v1
    kind: Step
    name: kaniko
    image: relaysh/kaniko-step-image-build
    spec:
      dockerhub: !Secret dockerhub
      destination: !Parameter imageName
      git:
        connection: !Connection {type: ssh, name: my-ssh-connection}
        name: !Parameter name
        branch: !Parameter gitBranch
        repository: !Parameter gitRepository
- summary: Build a docker image and push to GCR
  content:
    apiVersion: v1
    kind: Step
    name: kaniko
    image: relaysh/kaniko-step-image-build
    spec:
      google:
        connection: !Connection {type: gcp, name: my-gcp-connection}
      destination: !Parameter imageName
      git:
        connection: !Connection {type: ssh, name: my-ssh-connection}
        name: !Parameter name
        branch: !Parameter gitBranch
        repository: !Parameter gitRepository
